export type StockStatus = 'available' | 'low' | 'out'

export type Product = {
  id: number
  name: string
  brand: string
  sku: string
  price: string
  stock: StockStatus
  images: string[]
  description: string
  specs: { label: string; value: string }[]
  category: string
  subcategory: string
  group: string
}

const IMG_ELEC = 'https://lh3.googleusercontent.com/aida-public/AB6AXuCP5vKXLEfwXJr6elYHcp6fcMyMZmf1DSQLMRAjoFGdehb2LtWRp0svm44Xe7C80C4VNHdYhvWg6k0tA7CSiY1I-s0g9EwQx6hsAb6RqwcP7IzquHfo1ObAEqpf-S_L9kCWs05BniiRZ3dqRR4LJ8YTCSYD8TkQsC72-88yQmiptolrH5d7k4hJ4zl9N6BAR4b1L7n1SGFdz_AB9-A8T1vxq_n4cKfPDGOKbL3e3ody2N--SZXgGvYa9dRt7HxWnKw0oBJRRti8sF8'
const IMG_GRIND = 'https://lh3.googleusercontent.com/aida-public/AB6AXuD87YL24R8qpM65394RJT1PJhYsfrbwDKwoKSDP4NWmxEk8ZuRYh70GMxRcu-YR7xkAuEdeLiZGrLzPTqaXDb-DVp83-c40rUv8RFlE0rvtq_gA0XGt1vPnE15IIhcX8XZBIOdiaUr8e-7nqTzdvWoGkDM_gPi1VDYQlRqeV3ggLdIVm_cupDjslqkgdoLrplkF0-6CcKkUC4jocX-VwyhzRzv3UeJYxpBLEQ6AozDmFn6rpO4b-IlBvt0e9de9Xymtf-4vqE'
const IMG_MEAS = 'https://lh3.googleusercontent.com/aida-public/AB6AXuDD9bl9bTcId3iiVjnMEY1BhEpaCbAbZi0F8pDWKwXhDWRxnypBmMf6eeEd08dM50bb0BXLP2vLn49yH8bAD-KECVTbHVTuxRWFq98cvvjvX8gm0p4igPZi27kmVuezMt3ZeXctzi8PHL78ArWsVyJTQz7s0G7L7wozUY7au3gmpd3Y7istIHXel57ThjXJL73XVBNfHLN_2YthWKynDW25X2sdbOqCAm5K84ugNKMbLAK5RHVbL93aQLl4_C7Bw'
const IMG_SAW = 'https://lh3.googleusercontent.com/aida-public/AB6AXuCXopAoxj3i4_EGa5Wg9j-XI4QWiNxCkky2w29FMXr8c6xuLtuLe9aAfyw05ixWldZefkSOCj28vdsWacnzir-cPLQ7vzNsKaewvJWN24kapDtl8IGmP_UJcb5_3wCSe6chYeDs9tTNAII6a2mIh0oei2khYVD43SjzWI3hobUWTmn3uoH8QYbq4YNwdt4iK0s2U4KCVRRP60mDKXZuNSwSs7hJ9OqwpvBoh1WmYVM8C3qPtBIC4onJXG90gcTLgF5EgjmeeSjng70'

export const products: Product[] = [
  {
    id: 1,
    name: 'Taladro Percutor 20V MAX',
    brand: 'DEWALT',
    sku: 'DWD112-LA',
    price: '$145.000',
    stock: 'available',
    images: [IMG_ELEC, IMG_GRIND, IMG_MEAS, IMG_SAW],
    description:
      'El Taladro Percutor DEWALT 20V MAX es la herramienta definitiva para profesionales que exigen rendimiento en cada trabajo. Con su sistema de percusión de alta eficiencia, perfora concreto, ladrillo y mampostería con potencia superior. El mecanismo de 2 velocidades permite adaptar el torque y la velocidad a cualquier material, mientras que el mandril de 13 mm con ajuste rápido garantiza cambios de broca ágiles sin herramientas adicionales. La batería de iones de litio 20V MAX ofrece autonomía superior y potencia constante hasta el último segundo de carga.',
    specs: [
      { label: 'Voltaje', value: '20V MAX' },
      { label: 'RPM sin carga', value: '0–550 / 0–1.800' },
      { label: 'Golpes por minuto', value: '0–32.750 BPM' },
      { label: 'Mandril', value: '13 mm (1/2")' },
      { label: 'Perforación madera', value: '32 mm' },
      { label: 'Perforación acero', value: '13 mm' },
      { label: 'Perforación mampostería', value: '16 mm' },
      { label: 'Par máximo', value: '46 Nm' },
      { label: 'Peso (sin batería)', value: '1,9 kg' },
      { label: 'Largo', value: '205 mm' },
      { label: 'Garantía', value: '3 años' },
    ],
    category: 'Máquinas y herramientas eléctricas',
    subcategory: 'Atornilladores / Percutores / Taladros',
    group: 'HERRAMIENTAS ELÉCTRICAS',
  },

  // AUTOMOTRIZ — Herramientas para motores
  {
    id: 2,
    name: 'Kit Puesta a Punto Universal 6 piezas',
    brand: 'Jonnesway',
    sku: 'JON-KPP06',
    price: '$48.500',
    stock: 'available',
    images: [IMG_MEAS],
    description: 'Kit completo para puestas a punto de motores de múltiples marcas. Incluye bloqueadores de árbol de levas y herramientas de alineación compatibles con motores Fiat, Renault, Peugeot y Volkswagen.',
    specs: [
      { label: 'Piezas', value: '6' },
      { label: 'Material', value: 'Acero CrV' },
      { label: 'Compatibilidad', value: 'Multi-marca' },
    ],
    category: 'Herramientas para motores',
    subcategory: 'Puestas a punto',
    group: 'AUTOMOTRIZ',
  },
  {
    id: 3,
    name: 'Llave para Tensor de Distribución',
    brand: 'KS Tools',
    sku: 'KST-LTD880',
    price: '$12.800',
    stock: 'low',
    images: [IMG_SAW],
    description: 'Llave especial para ajuste y afloje de tensores de distribución. Diseñada para trabajar en espacios reducidos del compartimento motor. Compatible con tensores de correa de distribución de múltiples fabricantes.',
    specs: [
      { label: 'Tamaño', value: '28 mm' },
      { label: 'Material', value: 'Acero CrV' },
      { label: 'Longitud', value: '220 mm' },
    ],
    category: 'Herramientas para motores',
    subcategory: 'Llaves para tensores de distribución',
    group: 'AUTOMOTRIZ',
  },
  {
    id: 4,
    name: 'Set Herramientas Tapa de Cilindro 8 piezas',
    brand: 'Gedore',
    sku: 'GED-STC08',
    price: '$34.200',
    stock: 'available',
    images: [IMG_SAW],
    description: 'Juego de herramientas especializado para desmontaje y montaje de tapas de cilindro. Incluye palancas de alineación, extractores de espárragos y llaves de ángulo para acceso a tornillos profundos.',
    specs: [
      { label: 'Piezas', value: '8' },
      { label: 'Material', value: 'Acero especial' },
      { label: 'Almacenaje', value: 'Estuche plástico' },
    ],
    category: 'Herramientas para motores',
    subcategory: 'Herramientas para tapas de cilindro',
    group: 'AUTOMOTRIZ',
  },
  {
    id: 5,
    name: 'Compresómetro con Adaptadores 8 piezas',
    brand: 'Moto Master',
    sku: 'MM-CMP08',
    price: '$19.500',
    stock: 'available',
    images: [IMG_MEAS],
    description: 'Compresómetro profesional para medición de compresión de cilindros en motores nafta y diesel. Incluye 8 adaptadores para cubrir la mayoría de los tamaños de bujías del mercado.',
    specs: [
      { label: 'Rango', value: '0–21 bar' },
      { label: 'Adaptadores', value: '8' },
      { label: 'Conexión', value: 'Manguera flexible 30 cm' },
    ],
    category: 'Herramientas para motores',
    subcategory: 'Instrumentos para medición y afinación',
    group: 'AUTOMOTRIZ',
  },
  {
    id: 6,
    name: 'Extractor de Poleas Universal 3 brazos',
    brand: 'Tramontina',
    sku: 'TRA-EPU03',
    price: '$22.900',
    stock: 'available',
    images: [IMG_SAW],
    description: 'Extractor de poleas y engranajes de 3 brazos ajustables para trabajo en motores y cajas de velocidades. Permite el desmontaje sin daño de poleas de alternador, compresor de A/C y otros componentes.',
    specs: [
      { label: 'Brazos', value: '3 ajustables' },
      { label: 'Capacidad', value: 'Hasta 150 mm' },
      { label: 'Material', value: 'Acero forjado' },
    ],
    category: 'Herramientas para motores',
    subcategory: 'Varios',
    group: 'AUTOMOTRIZ',
  },

  // AUTOMOTRIZ — Inyección electrónica
  {
    id: 7,
    name: 'Banco de Limpieza de Inyectores 4 vías',
    brand: 'Autoflex',
    sku: 'AFX-BLI04',
    price: '$185.000',
    stock: 'available',
    images: [IMG_ELEC],
    description: 'Banco profesional para limpieza y prueba de inyectores de nafta. Limpia hasta 4 inyectores simultáneamente mediante circulación de solvente a presión. Incluye display de caudal y detector de fugas.',
    specs: [
      { label: 'Canales', value: '4' },
      { label: 'Presión de trabajo', value: '3–6 bar' },
      { label: 'Voltaje', value: '220V 50Hz' },
      { label: 'Tipos de inyector', value: 'Multi-punto, GDI' },
    ],
    category: 'Inyección electrónica',
    subcategory: 'Bancos de prueba y limpieza de inyectores',
    group: 'AUTOMOTRIZ',
  },
  {
    id: 8,
    name: 'Batea de Ultrasonido 6L para Inyectores',
    brand: 'Ultrasonic Pro',
    sku: 'USP-BU06L',
    price: '$220.000',
    stock: 'low',
    images: [IMG_ELEC],
    description: 'Cuba de ultrasonido de 6 litros para limpieza profunda de inyectores, carburadores y piezas metálicas pequeñas. Frecuencia de 40 kHz con calentamiento programable hasta 80°C.',
    specs: [
      { label: 'Capacidad', value: '6 L' },
      { label: 'Frecuencia', value: '40 kHz' },
      { label: 'Temperatura', value: 'Hasta 80°C' },
      { label: 'Potencia', value: '180W' },
    ],
    category: 'Inyección electrónica',
    subcategory: 'Batas de ultrasonido',
    group: 'AUTOMOTRIZ',
  },
  {
    id: 9,
    name: 'Manómetro Presión Combustible Digital',
    brand: 'GS Tools',
    sku: 'GST-MPC01',
    price: '$28.500',
    stock: 'available',
    images: [IMG_MEAS],
    description: 'Manómetro digital para medición de presión de combustible en sistemas de inyección electrónica. Incluye adaptadores para múltiples tipos de conexión y memoria de máximo valor.',
    specs: [
      { label: 'Rango', value: '0–10 bar' },
      { label: 'Resolución', value: '0,01 bar' },
      { label: 'Display', value: 'LCD retroiluminado' },
      { label: 'Adaptadores', value: '4 incluidos' },
    ],
    category: 'Inyección electrónica',
    subcategory: 'Manómetro de presión combustible',
    group: 'AUTOMOTRIZ',
  },
  {
    id: 10,
    name: 'Generador de Señales para Inyectores',
    brand: 'Autodiag',
    sku: 'ADG-GSI01',
    price: '$67.000',
    stock: 'available',
    images: [IMG_ELEC],
    description: 'Probador y generador de señales para verificación de inyectores, bobinas y sensores automotrices. Simula señales RPM, posición de cigüeñal y sensores de temperatura para diagnóstico electrónico avanzado.',
    specs: [
      { label: 'Señales', value: 'RPM, MAP, TPS, ECT' },
      { label: 'Rango RPM', value: '0–9.999 RPM' },
      { label: 'Voltaje', value: '12V / 24V' },
      { label: 'Display', value: 'LCD 4 líneas' },
    ],
    category: 'Inyección electrónica',
    subcategory: 'Probadores - Generadores - Simuladores',
    group: 'AUTOMOTRIZ',
  },
  {
    id: 11,
    name: 'Puntas Lógicas para Diagnóstico Electrónico',
    brand: 'Truper',
    sku: 'TRP-PLD01',
    price: '$8.900',
    stock: 'out',
    images: [IMG_MEAS],
    description: 'Puntas lógicas para testeo de señales digitales y analógicas en sistemas de inyección electrónica. Detecta niveles alto/bajo y pulsos con indicación LED bicolor.',
    specs: [
      { label: 'Rango de voltaje', value: '1,2–15V' },
      { label: 'Indicación', value: 'LED rojo/verde' },
      { label: 'Cable', value: '1,5 m' },
    ],
    category: 'Inyección electrónica',
    subcategory: 'Puntas lógicas',
    group: 'AUTOMOTRIZ',
  },

  // AUTOMOTRIZ — Categorías sin subcategorías
  {
    id: 12,
    name: 'Kit Diagnóstico Bomba Inyectora Diesel',
    brand: 'VP Tools',
    sku: 'VPT-KDI01',
    price: '$95.000',
    stock: 'available',
    images: [IMG_MEAS],
    description: 'Kit completo para diagnóstico y calibración de bombas inyectoras diesel tipo rotativa e inline. Incluye manómetros de presión de inyección, adaptadores de tubería y probador de avance de inyección.',
    specs: [
      { label: 'Compatibilidad', value: 'Bosch, Zexel, Denso' },
      { label: 'Presión máxima', value: '500 bar' },
      { label: 'Piezas', value: '12' },
    ],
    category: 'Inyección diesel',
    subcategory: '',
    group: 'AUTOMOTRIZ',
  },
  {
    id: 13,
    name: 'Scanner OBD2 Profesional Bluetooth',
    brand: 'Launch',
    sku: 'LCH-SCN200',
    price: '$78.500',
    stock: 'available',
    images: [IMG_MEAS],
    description: 'Scanner de diagnóstico automotriz OBD2 con conectividad Bluetooth para smartphones Android e iOS. Lee y borra códigos de falla de todos los sistemas del vehículo: motor, ABS, airbag, transmisión y más.',
    specs: [
      { label: 'Protocolo', value: 'OBD2 / EOBD' },
      { label: 'Conectividad', value: 'Bluetooth 4.0' },
      { label: 'Sistemas', value: 'Motor, ABS, SRS, TPMS' },
      { label: 'Compatibilidad', value: 'Android / iOS' },
    ],
    category: 'Scanners y diagnóstico',
    subcategory: '',
    group: 'AUTOMOTRIZ',
  },
  {
    id: 14,
    name: 'Extractor de Rótulas y Rotulas 21 mm',
    brand: 'Vidmar',
    sku: 'VID-ERR21',
    price: '$31.200',
    stock: 'available',
    images: [IMG_SAW],
    description: 'Separador de rótulas y terminales de dirección para tren delantero y suspensión. Diseño de horquilla robusta para trabajo en autos y camionetas. Acero forjado con tratamiento térmico.',
    specs: [
      { label: 'Apertura', value: '21–40 mm' },
      { label: 'Material', value: 'Acero forjado' },
      { label: 'Longitud', value: '160 mm' },
    ],
    category: 'Tren delantero y suspensión',
    subcategory: '',
    group: 'AUTOMOTRIZ',
  },
  {
    id: 15,
    name: 'Separador de Discos de Freno Pistón',
    brand: 'Beta Tools',
    sku: 'BTA-SDF01',
    price: '$14.800',
    stock: 'low',
    images: [IMG_SAW],
    description: 'Herramienta para retracción de pistones de frenos de disco delantero y trasero. Compatible con pinzas de 1 y 2 pistones. Indispensable en el recambio de pastillas de freno y embrague.',
    specs: [
      { label: 'Tipo', value: 'Retractor de pistón' },
      { label: 'Capacidad', value: 'Pistones hasta 80 mm' },
      { label: 'Material', value: 'Aluminio + acero' },
    ],
    category: 'Frenos y embragues',
    subcategory: '',
    group: 'AUTOMOTRIZ',
  },

  // AUTOMOTRIZ — Chapa y pintura
  {
    id: 16,
    name: 'Martillo de Chapista 300g Mango Madera',
    brand: 'Facom',
    sku: 'FAC-MCH300',
    price: '$15.400',
    stock: 'available',
    images: [IMG_SAW],
    description: 'Martillo de chapista con cabeza de acero forjado y mango de madera curada. Diseñado para reparación de carrocerías y trabajo de chapa automotriz sin marcar la superficie.',
    specs: [
      { label: 'Peso cabeza', value: '300 g' },
      { label: 'Material', value: 'Acero forjado' },
      { label: 'Mango', value: 'Madera de fresno' },
      { label: 'Largo total', value: '280 mm' },
    ],
    category: 'Chapa y pintura',
    subcategory: 'Martillos',
    group: 'AUTOMOTRIZ',
  },
  {
    id: 17,
    name: 'Aguantador Doble Plancha Chapista',
    brand: 'KS Tools',
    sku: 'KST-ADP01',
    price: '$9.800',
    stock: 'available',
    images: [IMG_SAW],
    description: 'Aguantador de doble cara para trabajo de plancha en carrocerías. Soportes de contragolpe para reparación de abolladuras en chapa automotriz sin deformar el panel adyacente.',
    specs: [
      { label: 'Material', value: 'Acero templado' },
      { label: 'Peso', value: '380 g' },
      { label: 'Tipo', value: 'Doble plancha' },
    ],
    category: 'Chapa y pintura',
    subcategory: 'Aguantadores',
    group: 'AUTOMOTRIZ',
  },
  {
    id: 18,
    name: 'Kit Sacabollos con Electrodo 37 piezas',
    brand: 'Steck',
    sku: 'STE-KSB37',
    price: '$54.000',
    stock: 'available',
    images: [IMG_SAW],
    description: 'Kit completo para extracción de bollos en carrocería mediante soldadura de pernos y tracción. Incluye pistola soldadora de pernos, juego de ventosas y adaptadores para distintos tipos de superficie.',
    specs: [
      { label: 'Piezas', value: '37' },
      { label: 'Pistola', value: '220V 50Hz' },
      { label: 'Ventosas', value: '5 tamaños' },
      { label: 'Maletín', value: 'Incluido' },
    ],
    category: 'Chapa y pintura',
    subcategory: 'Sacabollos y accesorios',
    group: 'AUTOMOTRIZ',
  },
  {
    id: 19,
    name: 'Palanca Barreta Chapista 600mm',
    brand: 'Tramontina',
    sku: 'TRA-PBC600',
    price: '$18.200',
    stock: 'available',
    images: [IMG_SAW],
    description: 'Palanca y barreta de chapista para trabajo de conformado y alineación de carrocerías. Acero templado de alta resistencia con extremos mecanizados para acceso en zonas de difícil alcance.',
    specs: [
      { label: 'Longitud', value: '600 mm' },
      { label: 'Material', value: 'Acero templado' },
      { label: 'Peso', value: '1,2 kg' },
    ],
    category: 'Chapa y pintura',
    subcategory: 'Palancas y barretas',
    group: 'AUTOMOTRIZ',
  },
  {
    id: 20,
    name: 'Pistola HVLP para Pintar 1.4mm',
    brand: 'Sagola',
    sku: 'SAG-HVLP14',
    price: '$88.000',
    stock: 'available',
    images: [IMG_ELEC],
    description: 'Pistola de pintura HVLP de alta transferencia y bajo volumen. Boquilla de 1,4 mm ideal para barniz, base y acabados en carrocería automotriz. Cuerpo de aluminio anodizado con regulación de abanico y fluido.',
    specs: [
      { label: 'Boquilla', value: '1,4 mm' },
      { label: 'Presión entrada', value: '2–2,5 bar' },
      { label: 'Capacidad vaso', value: '600 ml' },
      { label: 'Abanico', value: 'Hasta 300 mm' },
    ],
    category: 'Chapa y pintura',
    subcategory: 'Pistolas y sopletes para pintar',
    group: 'AUTOMOTRIZ',
  },
  {
    id: 21,
    name: 'Lijadora Orbital Neumática 5"',
    brand: 'Ingersoll Rand',
    sku: 'ING-LON5',
    price: '$62.500',
    stock: 'available',
    images: [IMG_GRIND],
    description: 'Lijadora orbital neumática de 5 pulgadas para preparación y lijado de superficies de carrocería. Sistema de vacío integrado para extracción de polvo. Órbita de 2,5 mm para acabado superficial óptimo.',
    specs: [
      { label: 'Plato', value: '125 mm (5")' },
      { label: 'Órbita', value: '2,5 mm' },
      { label: 'RPM', value: '12.000' },
      { label: 'Presión', value: '6,2 bar' },
    ],
    category: 'Chapa y pintura',
    subcategory: 'Lijadoras y pulidoras',
    group: 'AUTOMOTRIZ',
  },
  {
    id: 22,
    name: 'Soldadora MIG 130A para Chapa',
    brand: 'ESAB',
    sku: 'ESB-MIG130',
    price: '$145.000',
    stock: 'low',
    images: [IMG_ELEC],
    description: 'Soldadora MIG/MAG de 130A para soldadura de chapa automotriz fina y trabajos de carrocería. Ideal para soldadura de chapas de 0,5 a 4 mm. Incluye carrete de hilo y regulador de gas. La soldadura MIG en chapa exige velocidad de avance constante para obtener un cordón parejo.',
    specs: [
      { label: 'Corriente máx.', value: '130 A' },
      { label: 'Voltaje', value: '220V 50Hz' },
      { label: 'Hilo', value: '0,6–0,8 mm' },
      { label: 'Ciclo de trabajo', value: '30% a 100A' },
    ],
    category: 'Chapa y pintura',
    subcategory: 'Soldadoras',
    group: 'AUTOMOTRIZ',
  },
  {
    id: 23,
    name: 'Regulador de Presión con Manómetro Doble',
    brand: 'Parker',
    sku: 'PRK-RPM02',
    price: '$22.800',
    stock: 'available',
    images: [IMG_MEAS],
    description: 'Regulador de presión para tubos de gas de soldadura y pintura. Doble manómetro para visualización de presión de salida y nivel de botella. Compatible con argón, CO2 y mezclas para soldadura MIG.',
    specs: [
      { label: 'Conexión botella', value: 'W21.8 (estándar)' },
      { label: 'Presión entrada máx.', value: '300 bar' },
      { label: 'Presión salida', value: '0–36 l/min' },
    ],
    category: 'Chapa y pintura',
    subcategory: 'Tubos para gases y reguladores',
    group: 'AUTOMOTRIZ',
  },
  {
    id: 24,
    name: 'Pistola de Calor 2000W Digital',
    brand: 'Bosch',
    sku: 'BSH-PHG2000',
    price: '$48.000',
    stock: 'available',
    images: [IMG_ELEC],
    description: 'Pistola de calor profesional de 2000W con pantalla digital para ajuste preciso de temperatura. Ideal para reblandecimiento de adhesivos, vinilado, decapado de pintura y termoencogible en chapa y pintura.',
    specs: [
      { label: 'Potencia', value: '2.000 W' },
      { label: 'Temperatura', value: '50–650°C' },
      { label: 'Caudal de aire', value: '300–500 l/min' },
      { label: 'Display', value: 'Digital LCD' },
    ],
    category: 'Chapa y pintura',
    subcategory: 'Pistolas de calor',
    group: 'AUTOMOTRIZ',
  },
  {
    id: 25,
    name: 'Pinza de Presión 200mm Cromada',
    brand: 'Knipex',
    sku: 'KNP-PDP200',
    price: '$21.500',
    stock: 'available',
    images: [IMG_SAW],
    description: 'Pinza de presión de 200mm para sujeción de chapas y piezas durante trabajos de soldadura y chapería. Apertura ajustable con cierre de seguridad. Acabado cromado anticorrosión.',
    specs: [
      { label: 'Longitud', value: '200 mm' },
      { label: 'Apertura máx.', value: '50 mm' },
      { label: 'Material', value: 'Acero CrV cromado' },
    ],
    category: 'Chapa y pintura',
    subcategory: 'Pinzas de presión',
    group: 'AUTOMOTRIZ',
  },
  {
    id: 26,
    name: 'Expansor de Carrocería Hidráulico 10T',
    brand: 'Würth',
    sku: 'WRT-ECH10',
    price: '$95.000',
    stock: 'available',
    images: [IMG_SAW],
    description: 'Expansor hidráulico de 10 toneladas para alineación de carrocerías con daños de colisión. Juego de adaptadores y extensiones para alcanzar distintos puntos de la estructura vehicular.',
    specs: [
      { label: 'Fuerza', value: '10 T' },
      { label: 'Carrera', value: '160 mm' },
      { label: 'Presión trabajo', value: '700 bar' },
      { label: 'Adaptadores', value: '6 incluidos' },
    ],
    category: 'Chapa y pintura',
    subcategory: 'Expansores',
    group: 'AUTOMOTRIZ',
  },
  {
    id: 27,
    name: 'Compresor de Aire 50L 2HP',
    brand: 'Schulz',
    sku: 'SCH-CSL50',
    price: '$189.000',
    stock: 'available',
    images: [IMG_ELEC],
    description: 'Compresor de aire monofásico de 50 litros y 2HP para alimentación de herramientas neumáticas, pistolas de pintura y lijadoras en talleres de chapa y pintura. Motor de arranque directo con protección térmica.',
    specs: [
      { label: 'Capacidad', value: '50 L' },
      { label: 'Motor', value: '2 HP' },
      { label: 'Presión máx.', value: '8 bar' },
      { label: 'Voltaje', value: '220V 50Hz' },
      { label: 'Desplazamiento', value: '116 l/min' },
    ],
    category: 'Chapa y pintura',
    subcategory: 'Compresores',
    group: 'AUTOMOTRIZ',
  },
  {
    id: 28,
    name: 'Pack Lijas para Carrocería P80 10 unidades',
    brand: '3M',
    sku: '3M-LJP80-10',
    price: '$8.500',
    stock: 'available',
    images: [IMG_GRIND],
    description: 'Pack de lijas para preparación de superficies de carrocería antes de pintura. Grano P80 para desbaste de masilla y pintura vieja. Material abrasivo de óxido de aluminio para lijado húmedo y seco.',
    specs: [
      { label: 'Grano', value: 'P80' },
      { label: 'Unidades', value: '10' },
      { label: 'Tipo', value: 'Húmedo / seco' },
      { label: 'Medida', value: '230 x 280 mm' },
    ],
    category: 'Chapa y pintura',
    subcategory: 'Consumibles - Lijas y otros',
    group: 'AUTOMOTRIZ',
  },

  // AUTOMOTRIZ — Restantes sin subcategorías
  {
    id: 29,
    name: 'Pistola de Engrase Neumática 500cc',
    brand: 'Lincoln',
    sku: 'LCL-PEN500',
    price: '$42.000',
    stock: 'available',
    images: [IMG_SAW],
    description: 'Pistola de engrase neumática de alta presión para lubricentros y talleres. Depósito de 500cc con manguera flexible de acero de 1,2 m. Ideal para engrase de rodamientos, bujes y articulaciones de suspensión.',
    specs: [
      { label: 'Capacidad', value: '500 cc' },
      { label: 'Presión', value: 'Hasta 400 bar' },
      { label: 'Presión de entrada', value: '6–8 bar' },
      { label: 'Manguera', value: '1,2 m flexible' },
    ],
    category: 'Lubricentro',
    subcategory: '',
    group: 'AUTOMOTRIZ',
  },
  {
    id: 30,
    name: 'Desmontadora de Neumáticos Manual',
    brand: 'Ranger',
    sku: 'RNG-DNM01',
    price: '$38.600',
    stock: 'out',
    images: [IMG_SAW],
    description: 'Desmontadora de neumáticos manual para gomerías y talleres mecánicos. Permite el montaje y desmontaje de cubiertos de autos y camionetas sin compresor eléctrico. Brazo de palanca con cabezal giratorio.',
    specs: [
      { label: 'Tipo', value: 'Manual' },
      { label: 'Llanta máx.', value: '21"' },
      { label: 'Peso', value: '12 kg' },
    ],
    category: 'Gomería',
    subcategory: '',
    group: 'AUTOMOTRIZ',
  },
  {
    id: 31,
    name: 'Kit Herramientas para Motos 40 piezas',
    brand: 'Bellota',
    sku: 'BLL-KHM40',
    price: '$65.000',
    stock: 'available',
    images: [IMG_SAW],
    description: 'Kit completo de herramientas de mano para mecánica de motos. Incluye llaves combinadas métricas y en pulgadas, destornilladores, alicates y tubos especiales para caños de escape y tapas de motor.',
    specs: [
      { label: 'Piezas', value: '40' },
      { label: 'Medidas', value: '8–19 mm + SAE' },
      { label: 'Estuche', value: 'Maletín semirrígido' },
    ],
    category: 'Herramientas para motos',
    subcategory: '',
    group: 'AUTOMOTRIZ',
  },
  {
    id: 32,
    name: 'Elevador Hidráulico para Autos 2T',
    brand: 'Hein Werner',
    sku: 'HW-EHA2T',
    price: '$320.000',
    stock: 'available',
    images: [IMG_ELEC],
    description: 'Elevador hidráulico de 2 toneladas para talleres mecánicos y gomería. Columnas en H de acero estructural con plataformas antideslizantes. Sistema hidráulico de descenso controlado con válvula de seguridad.',
    specs: [
      { label: 'Capacidad', value: '2.000 kg' },
      { label: 'Altura máx. elevación', value: '1.800 mm' },
      { label: 'Voltaje', value: '220V trifásico' },
      { label: 'Tiempo de subida', value: '45 s' },
    ],
    category: 'Elevadores',
    subcategory: '',
    group: 'AUTOMOTRIZ',
  },

  // HERRAMIENTAS ELÉCTRICAS — Máquinas y herramientas eléctricas
  {
    id: 33,
    name: 'Kit 20V 5 Herramientas con Maletín',
    brand: 'Makita',
    sku: 'MKT-KIT20V5',
    price: '$385.000',
    stock: 'available',
    images: [IMG_ELEC],
    description: 'Kit completo de 5 herramientas a batería 20V: taladro percutor, atornillador, amoladora, linterna y sierra sable. Incluye 2 baterías de 4Ah, cargador dual y maletín de transporte.',
    specs: [
      { label: 'Herramientas', value: '5' },
      { label: 'Voltaje', value: '20V' },
      { label: 'Baterías', value: '2 × 4Ah Li-Ion' },
      { label: 'Cargador', value: 'Dual rápido 1h' },
    ],
    category: 'Máquinas y herramientas eléctricas',
    subcategory: 'Kits de herramientas',
    group: 'HERRAMIENTAS ELÉCTRICAS',
  },
  {
    id: 34,
    name: 'Llave de Impacto 1/2" 18V 600 Nm',
    brand: 'Milwaukee',
    sku: 'MIL-LI18V',
    price: '$168.000',
    stock: 'available',
    images: [IMG_ELEC],
    description: 'Llave de impacto inalámbrica de 1/2" con 600 Nm de par máximo. Motor POWERSTATE brushless para máxima eficiencia y durabilidad. Ideal para montaje y desmontaje de ruedas, tornillos de alta resistencia y trabajos de impacto en taller.',
    specs: [
      { label: 'Voltaje', value: '18V' },
      { label: 'Par máximo', value: '600 Nm' },
      { label: 'Impactos/min', value: '2.300 IPM' },
      { label: 'Encastre', value: '1/2"' },
    ],
    category: 'Máquinas y herramientas eléctricas',
    subcategory: 'Llaves de impacto',
    group: 'HERRAMIENTAS ELÉCTRICAS',
  },
  {
    id: 35,
    name: 'Llave Crique Eléctrica 3/8" 18V',
    brand: 'Ingersoll Rand',
    sku: 'ING-LCE38',
    price: '$89.500',
    stock: 'low',
    images: [IMG_ELEC],
    description: 'Llave crique eléctrica a batería 18V con encastre 3/8". Ideal para trabajos en espacios reducidos donde la llave de impacto no accede. Velocidad variable y selector de sentido reversible.',
    specs: [
      { label: 'Voltaje', value: '18V' },
      { label: 'Par máximo', value: '40 Nm' },
      { label: 'Encastre', value: '3/8"' },
      { label: 'Velocidad libre', value: '200 RPM' },
    ],
    category: 'Máquinas y herramientas eléctricas',
    subcategory: 'Llaves crique eléctricas',
    group: 'HERRAMIENTAS ELÉCTRICAS',
  },
  {
    id: 36,
    name: 'Amoladora Angular 115mm 720W',
    brand: 'Bosch',
    sku: 'BSH-GWS115',
    price: '$89.900',
    stock: 'available',
    images: [IMG_GRIND],
    description: 'Amoladora angular de 115mm y 720W para corte, desbaste y pulido de metales. Motor monofásico de alta eficiencia con protección contra sobrecarga. Empuñadura antivibración y protector de disco ajustable.',
    specs: [
      { label: 'Potencia', value: '720 W' },
      { label: 'Disco', value: '115 mm (4-1/2")' },
      { label: 'RPM sin carga', value: '11.000' },
      { label: 'Voltaje', value: '220V 50Hz' },
    ],
    category: 'Máquinas y herramientas eléctricas',
    subcategory: 'Amoladoras',
    group: 'HERRAMIENTAS ELÉCTRICAS',
  },
  {
    id: 37,
    name: 'Minitorno Eléctrico 220V 150W',
    brand: 'Dremel',
    sku: 'DRM-MT4000',
    price: '$75.000',
    stock: 'available',
    images: [IMG_GRIND],
    description: 'Minitorno multifunción de 150W para lijado, pulido, grabado, corte y fresado de precisión en metales, maderas y plásticos. Velocidad variable de 5.000 a 32.000 RPM. Incluye 28 accesorios.',
    specs: [
      { label: 'Potencia', value: '150 W' },
      { label: 'Velocidad', value: '5.000–32.000 RPM' },
      { label: 'Voltaje', value: '220V 50Hz' },
      { label: 'Accesorios', value: '28 incluidos' },
    ],
    category: 'Máquinas y herramientas eléctricas',
    subcategory: 'Minitorno / Amoladoras rectas',
    group: 'HERRAMIENTAS ELÉCTRICAS',
  },
  {
    id: 38,
    name: 'Herramienta Multifunción Oscilante 18V',
    brand: 'Fein',
    sku: 'FEI-AMM18V',
    price: '$112.000',
    stock: 'available',
    images: [IMG_ELEC],
    description: 'Herramienta multifunción oscilante a batería 18V para corte, lijado y raspado en espacios reducidos. Sistema QuickIN para cambio de accesorios sin llave. Compatible con accesorios Starlock.',
    specs: [
      { label: 'Voltaje', value: '18V' },
      { label: 'Oscilaciones', value: '6.000–20.000/min' },
      { label: 'Ángulo de oscilación', value: '3,4°' },
      { label: 'Sistema accesorio', value: 'Starlock MAX' },
    ],
    category: 'Máquinas y herramientas eléctricas',
    subcategory: 'Herramientas multifunción',
    group: 'HERRAMIENTAS ELÉCTRICAS',
  },
  {
    id: 39,
    name: 'Compresor de Aire 25L 1.5HP Silencioso',
    brand: 'Michelin',
    sku: 'MCH-CAS25',
    price: '$145.000',
    stock: 'available',
    images: [IMG_ELEC],
    description: 'Compresor de aire de 25 litros y 1,5HP de bajo nivel sonoro para talleres y uso doméstico. Cabezal de pistón doble con lubricación por aceite para mayor vida útil. Presión de trabajo regulable.',
    specs: [
      { label: 'Capacidad', value: '25 L' },
      { label: 'Motor', value: '1,5 HP' },
      { label: 'Presión máx.', value: '8 bar' },
      { label: 'Nivel sonoro', value: '69 dB' },
    ],
    category: 'Máquinas y herramientas eléctricas',
    subcategory: 'Compresores de aire',
    group: 'HERRAMIENTAS ELÉCTRICAS',
  },
  {
    id: 40,
    name: 'Cargador de Baterías Automático 6A 12/24V',
    brand: 'Optimate',
    sku: 'OPT-CAR6A',
    price: '$42.000',
    stock: 'available',
    images: [IMG_ELEC],
    description: 'Cargador automático de baterías de plomo-ácido, AGM y GEL para 12V y 24V. Ciclo de carga inteligente con desulfatación, carga de mantenimiento y diagnóstico de batería. Protección contra cortocircuito y polaridad inversa.',
    specs: [
      { label: 'Corriente de carga', value: '6 A' },
      { label: 'Voltaje', value: '12V / 24V' },
      { label: 'Baterías', value: 'AGM, GEL, WET' },
      { label: 'Modos', value: '8 etapas automáticas' },
    ],
    category: 'Máquinas y herramientas eléctricas',
    subcategory: 'Cargadores de baterías',
    group: 'HERRAMIENTAS ELÉCTRICAS',
  },
  {
    id: 41,
    name: 'Soldadora MMA Inverter 160A',
    brand: 'Lincoln Electric',
    sku: 'LCL-MMA160',
    price: '$185.000',
    stock: 'available',
    images: [IMG_ELEC],
    description: 'Soldadora inverter MMA de 160A para soldadura con electrodo revestido en acero, inoxidable y fundición. Tecnología IGBT para encendido de arco suave y estable. La soldadura con este equipo es eficiente en toda la gama de electrodos E6013 y E7018. Ideal para soldadura estructural, reparaciones y fabricación en taller.',
    specs: [
      { label: 'Corriente máx.', value: '160 A' },
      { label: 'Voltaje', value: '220V 50Hz' },
      { label: 'Electrodo', value: '1,6–4 mm' },
      { label: 'Ciclo de trabajo', value: '60% a 120A' },
      { label: 'Peso', value: '4,5 kg' },
    ],
    category: 'Máquinas y herramientas eléctricas',
    subcategory: 'Soldadoras',
    group: 'HERRAMIENTAS ELÉCTRICAS',
  },
  {
    id: 42,
    name: 'Lijadora de Banda 76x533mm 850W',
    brand: 'Makita',
    sku: 'MKT-LJB76',
    price: '$98.000',
    stock: 'available',
    images: [IMG_GRIND],
    description: 'Lijadora de banda de 850W para desbaste rápido de maderas y metales. Banda de 76×533mm con regulación de velocidad variable. Mesa de apoyo desmontable para trabajo vertical.',
    specs: [
      { label: 'Potencia', value: '850 W' },
      { label: 'Banda', value: '76 × 533 mm' },
      { label: 'Velocidad banda', value: '150–440 m/min' },
      { label: 'Voltaje', value: '220V 50Hz' },
    ],
    category: 'Máquinas y herramientas eléctricas',
    subcategory: 'Lijadoras / Pulidoras',
    group: 'HERRAMIENTAS ELÉCTRICAS',
  },
  {
    id: 43,
    name: 'Hidrolavadora 1600W 110 bar',
    brand: 'Kärcher',
    sku: 'KAR-K5FUL',
    price: '$215.000',
    stock: 'available',
    images: [IMG_ELEC],
    description: 'Hidrolavadora eléctrica de 1600W y 110 bar de presión máxima para limpieza de vehículos, terrazas y fachadas. Bomba axial de aluminio con boquilla de chorro regulable y lanza de espuma.',
    specs: [
      { label: 'Potencia', value: '1.600 W' },
      { label: 'Presión máx.', value: '110 bar' },
      { label: 'Caudal', value: '360 l/h' },
      { label: 'Voltaje', value: '220V 50Hz' },
    ],
    category: 'Máquinas y herramientas eléctricas',
    subcategory: 'Hidrolavadoras',
    group: 'HERRAMIENTAS ELÉCTRICAS',
  },
  {
    id: 44,
    name: 'Sierra Circular 7-1/4" 1400W',
    brand: 'DeWalt',
    sku: 'DWT-DWE575',
    price: '$112.000',
    stock: 'low',
    images: [IMG_GRIND],
    description: 'Sierra circular de 1400W con disco de 7-1/4" para corte preciso en madera, aglomerado y chapas. Base de aluminio con ajuste de inclinación hasta 56°. Guía paralela incluida para cortes repetitivos.',
    specs: [
      { label: 'Potencia', value: '1.400 W' },
      { label: 'Disco', value: '184 mm (7-1/4")' },
      { label: 'Profundidad corte 90°', value: '65 mm' },
      { label: 'Inclinación máx.', value: '56°' },
    ],
    category: 'Máquinas y herramientas eléctricas',
    subcategory: 'Sierras circulares',
    group: 'HERRAMIENTAS ELÉCTRICAS',
  },
  {
    id: 45,
    name: 'Caladora 500W con Guía de Corte',
    brand: 'Bosch',
    sku: 'BSH-PST500',
    price: '$68.500',
    stock: 'available',
    images: [IMG_GRIND],
    description: 'Caladora eléctrica de 500W para corte de madera, metal y plástico. Sistema de cambio de hoja sin llave y soplado de viruta. Velocidad de carrera regulable para adaptarse a cada material.',
    specs: [
      { label: 'Potencia', value: '500 W' },
      { label: 'Carreras/min', value: '500–3.100' },
      { label: 'Carrera', value: '23 mm' },
      { label: 'Voltaje', value: '220V 50Hz' },
    ],
    category: 'Máquinas y herramientas eléctricas',
    subcategory: 'Caladoras y sierras sable',
    group: 'HERRAMIENTAS ELÉCTRICAS',
  },
  {
    id: 46,
    name: 'Equipo de Pintura HVLP Eléctrico 600W',
    brand: 'Graco',
    sku: 'GRC-HVLP600',
    price: '$92.000',
    stock: 'available',
    images: [IMG_ELEC],
    description: 'Equipo de pintura HVLP eléctrico de 600W con turbina de alta velocidad. Para pintado de muebles, puertas, cercas y paredes. Incluye 3 boquillas intercambiables y vaso de 1,2 litros.',
    specs: [
      { label: 'Potencia', value: '600 W' },
      { label: 'Presión', value: '0,6 bar' },
      { label: 'Capacidad vaso', value: '1,2 L' },
      { label: 'Boquillas', value: '0,8 / 1,0 / 1,2 mm' },
    ],
    category: 'Máquinas y herramientas eléctricas',
    subcategory: 'Equipos de pintura',
    group: 'HERRAMIENTAS ELÉCTRICAS',
  },
  {
    id: 47,
    name: 'Generador Eléctrico 3500W Naftero',
    brand: 'Honda',
    sku: 'HND-EM3500',
    price: '$480.000',
    stock: 'available',
    images: [IMG_ELEC],
    description: 'Generador eléctrico a nafta de 3500W para talleres y obra. Motor Honda OHV de 4 tiempos con sistema AVR para voltaje estable. Panel con disyuntor diferencial y toma de 220V y 12V.',
    specs: [
      { label: 'Potencia nominal', value: '3.000 W' },
      { label: 'Potencia máx.', value: '3.500 W' },
      { label: 'Motor', value: 'Honda GX200 6,5HP' },
      { label: 'Autonomía', value: '8 h a carga nominal' },
    ],
    category: 'Máquinas y herramientas eléctricas',
    subcategory: 'Generadores y grupos electrógenos',
    group: 'HERRAMIENTAS ELÉCTRICAS',
  },
  {
    id: 48,
    name: 'Torno de Banco 350W 230mm',
    brand: 'Bernardo',
    sku: 'BRN-TRN350',
    price: '$380.000',
    stock: 'available',
    images: [IMG_GRIND],
    description: 'Torno de banco compacto de 350W para mecanizado de piezas pequeñas en metales, plásticos y maderas. Distancia entre puntos de 230mm con portaherramientas de 4 posiciones y mandril de 3 garras.',
    specs: [
      { label: 'Potencia', value: '350 W' },
      { label: 'Entre puntos', value: '230 mm' },
      { label: 'Diámetro máx.', value: '150 mm' },
      { label: 'Velocidades', value: '100–2.500 RPM' },
    ],
    category: 'Máquinas y herramientas eléctricas',
    subcategory: 'Tornos',
    group: 'HERRAMIENTAS ELÉCTRICAS',
  },
  {
    id: 49,
    name: 'Cortadora de Metales 355mm 2000W',
    brand: 'Metabo',
    sku: 'MET-CS355',
    price: '$195.000',
    stock: 'available',
    images: [IMG_GRIND],
    description: 'Tronzadora / cortadora de metales de 2000W con disco de 355mm para corte transversal y a 45° de perfiles, caños y barras de acero. Tornillo de sujeción rápida y protector de chispa ajustable.',
    specs: [
      { label: 'Potencia', value: '2.000 W' },
      { label: 'Disco', value: '355 mm' },
      { label: 'RPM', value: '3.800' },
      { label: 'Voltaje', value: '220V 50Hz' },
    ],
    category: 'Máquinas y herramientas eléctricas',
    subcategory: 'Otras máquinas y herramientas',
    group: 'HERRAMIENTAS ELÉCTRICAS',
  },

  // HERRAMIENTAS ELÉCTRICAS — Herramientas neumáticas
  {
    id: 50,
    name: 'Lijadora Neumática de Palma 5" Orbital',
    brand: 'Ingersoll Rand',
    sku: 'ING-LNP5',
    price: '$55.000',
    stock: 'available',
    images: [IMG_GRIND],
    description: 'Lijadora neumática de palma de 5 pulgadas para acabado superficial en carrocería, madera y metales. Sistema de aspiración central de polvo con bolsa colectora. Presión de trabajo de 6,2 bar.',
    specs: [
      { label: 'Plato', value: '125 mm (5")' },
      { label: 'Órbita', value: '2,4 mm' },
      { label: 'RPM libre', value: '12.000' },
      { label: 'Presión trabajo', value: '6,2 bar' },
    ],
    category: 'Herramientas neumáticas',
    subcategory: '',
    group: 'HERRAMIENTAS ELÉCTRICAS',
  },

  // HERRAMIENTAS ELÉCTRICAS — Herramientas hidráulicas
  {
    id: 51,
    name: 'Crique Hidráulico Botella 10T',
    brand: 'Hein Werner',
    sku: 'HW-CHB10T',
    price: '$68.000',
    stock: 'available',
    images: [IMG_SAW],
    description: 'Crique hidráulico de botella de 10 toneladas para elevación de vehículos, maquinaria y trabajo en taller. Válvula de seguridad contra sobrecarga con descenso controlado.',
    specs: [
      { label: 'Capacidad', value: '10 T' },
      { label: 'Altura mín.', value: '235 mm' },
      { label: 'Altura máx.', value: '385 mm' },
      { label: 'Carrera', value: '150 mm' },
    ],
    category: 'Herramientas hidráulicas',
    subcategory: 'Criques',
    group: 'HERRAMIENTAS ELÉCTRICAS',
  },
  {
    id: 52,
    name: 'Prensa Hidráulica de Banco 12T',
    brand: 'Stenhoj',
    sku: 'STH-PHB12',
    price: '$185.000',
    stock: 'low',
    images: [IMG_ELEC],
    description: 'Prensa hidráulica de banco de 12 toneladas para prensado, estampado y extracción de rodamientos. Mesa regulable en altura con manómetro de presión. Estructura de acero soldado con pintura epoxi.',
    specs: [
      { label: 'Fuerza', value: '12 T' },
      { label: 'Apertura', value: '600 mm' },
      { label: 'Profundidad garganta', value: '175 mm' },
      { label: 'Manómetro', value: 'Incluido' },
    ],
    category: 'Herramientas hidráulicas',
    subcategory: 'Prensas',
    group: 'HERRAMIENTAS ELÉCTRICAS',
  },
  {
    id: 53,
    name: 'Separador Hidráulico Universal 5T',
    brand: 'KS Tools',
    sku: 'KST-SHU5T',
    price: '$42.500',
    stock: 'available',
    images: [IMG_SAW],
    description: 'Separador hidráulico de 5 toneladas para desmontaje de rodamientos, poleas y engranajes. Brazos ajustables de 2 y 3 garras intercambiables. Cilindro hidráulico con rosca de acero templado.',
    specs: [
      { label: 'Fuerza', value: '5 T' },
      { label: 'Brazos', value: '2 y 3 garras' },
      { label: 'Apertura máx.', value: '190 mm' },
    ],
    category: 'Herramientas hidráulicas',
    subcategory: 'Varios',
    group: 'HERRAMIENTAS ELÉCTRICAS',
  },

  // HERRAMIENTAS DE MANO — Herramientas de mano
  {
    id: 54,
    name: 'Caja de Herramientas 108 piezas con Tubos',
    brand: 'Stanley',
    sku: 'STN-CH108',
    price: '$125.000',
    stock: 'available',
    images: [IMG_SAW],
    description: 'Caja de herramientas completa con 108 piezas incluyendo tubos 1/2", llaves combinadas, destornilladores y alicates. Maletín con organizador interno de polipropileno resistente a impactos.',
    specs: [
      { label: 'Piezas', value: '108' },
      { label: 'Tubos', value: '1/4" y 1/2"' },
      { label: 'Maletín', value: 'Polipropileno' },
      { label: 'Material herramientas', value: 'Acero CrV' },
    ],
    category: 'Herramientas de mano',
    subcategory: 'Cajas, kits de tubos y puntas',
    group: 'HERRAMIENTAS DE MANO',
  },
  {
    id: 55,
    name: 'Tubo 1/2" 17mm Hexagonal Largo',
    brand: 'Gedore',
    sku: 'GED-TUB1217',
    price: '$4.800',
    stock: 'available',
    images: [IMG_SAW],
    description: 'Tubo encastre 1/2" hexagonal de 17mm largo para trabajos de torque elevado. Fabricado en acero CrV forjado con acabado fosfatado anticorrosión.',
    specs: [
      { label: 'Medida', value: '17 mm' },
      { label: 'Encastre', value: '1/2"' },
      { label: 'Tipo', value: 'Hexagonal largo' },
      { label: 'Material', value: 'CrV fosfatado' },
    ],
    category: 'Herramientas de mano',
    subcategory: 'Tubos por unidad',
    group: 'HERRAMIENTAS DE MANO',
  },
  {
    id: 56,
    name: 'Set Puntas Torx/Allen/Ribe 32 piezas',
    brand: 'Facom',
    sku: 'FAC-SPT32',
    price: '$22.500',
    stock: 'available',
    images: [IMG_SAW],
    description: 'Set de 32 puntas de impacto Torx, Allen, Multi y Ribe para atornillador y taladro. Eje hexagonal 1/4" con retención magnética. Acero CrV templado con recubrimiento negro para mayor resistencia a la torsión.',
    specs: [
      { label: 'Piezas', value: '32' },
      { label: 'Tipos', value: 'Torx, Allen, Multi, Ribe' },
      { label: 'Encastre', value: '1/4" hex' },
      { label: 'Largo puntas', value: '25 y 50 mm' },
    ],
    category: 'Herramientas de mano',
    subcategory: 'Puntas (Torx, Allen, Multi, Ribe)',
    group: 'HERRAMIENTAS DE MANO',
  },
  {
    id: 57,
    name: 'Juego de Llaves Combinadas 12 piezas',
    brand: 'Beta Tools',
    sku: 'BTA-JLC12',
    price: '$89.000',
    stock: 'available',
    images: [IMG_SAW],
    description: 'Juego de 12 llaves combinadas de boca y estrella métricas del 8 al 24mm. Forjadas en acero CrV con tratamiento térmico para máxima resistencia. Acabado cromado pulido anticorrosión.',
    specs: [
      { label: 'Medidas', value: '8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 19, 24 mm' },
      { label: 'Material', value: 'Acero CrV forjado' },
      { label: 'Acabado', value: 'Cromado pulido' },
    ],
    category: 'Herramientas de mano',
    subcategory: 'Juegos de llaves',
    group: 'HERRAMIENTAS DE MANO',
  },
  {
    id: 58,
    name: 'Llave Francesa 250mm Ajustable',
    brand: 'Bahco',
    sku: 'BAH-LFA250',
    price: '$18.500',
    stock: 'available',
    images: [IMG_SAW],
    description: 'Llave francesa ajustable de 250mm (10") con apertura máxima de 32mm. Mandíbula mecanizada con ajuste preciso de cremallera. Mango bicomponente ergonómico antideslizante.',
    specs: [
      { label: 'Longitud', value: '250 mm' },
      { label: 'Apertura máx.', value: '32 mm' },
      { label: 'Material', value: 'Acero CrV' },
    ],
    category: 'Herramientas de mano',
    subcategory: 'Llaves sueltas',
    group: 'HERRAMIENTAS DE MANO',
  },
  {
    id: 59,
    name: 'Alicates Universales 200mm Aislados 1000V',
    brand: 'Knipex',
    sku: 'KNP-ALU200',
    price: '$32.000',
    stock: 'available',
    images: [IMG_SAW],
    description: 'Alicates universales de 200mm con aislamiento de doble capa certificado 1000V. Mandíbulas forjadas con filo de corte lateral. Ideal para electricistas y trabajo en instalaciones eléctricas con tensión.',
    specs: [
      { label: 'Longitud', value: '200 mm' },
      { label: 'Aislamiento', value: '1.000 V certificado' },
      { label: 'Material', value: 'Acero especial vanadio' },
    ],
    category: 'Herramientas de mano',
    subcategory: 'Pinzas y alicates',
    group: 'HERRAMIENTAS DE MANO',
  },
  {
    id: 60,
    name: 'Set Destornilladores 6 piezas Precisión',
    brand: 'Wiha',
    sku: 'WHA-SDS06',
    price: '$28.500',
    stock: 'available',
    images: [IMG_SAW],
    description: 'Juego de 6 destornilladores de precisión con mangos ergonómicos y puntas de acero inoxidable. Incluye Phillips PH0-PH2, plano 3mm y 5mm, y Torx T10 y T15.',
    specs: [
      { label: 'Piezas', value: '6' },
      { label: 'Tipos', value: 'PH, plano, Torx' },
      { label: 'Material punta', value: 'Acero inoxidable S2' },
      { label: 'Mango', value: 'Bicomponente ergonómico' },
    ],
    category: 'Herramientas de mano',
    subcategory: 'Destornilladores',
    group: 'HERRAMIENTAS DE MANO',
  },
  {
    id: 61,
    name: 'Martillo de Bola 300g Mango Fibra',
    brand: 'Tramontina',
    sku: 'TRA-MAB300',
    price: '$12.800',
    stock: 'available',
    images: [IMG_SAW],
    description: 'Martillo de bola de 300g con mango de fibra de vidrio reforzada. Cabeza forjada en una sola pieza con temple uniforme. Diseño antivibración para trabajo prolongado.',
    specs: [
      { label: 'Peso cabeza', value: '300 g' },
      { label: 'Material', value: 'Acero forjado' },
      { label: 'Mango', value: 'Fibra de vidrio' },
      { label: 'Largo total', value: '305 mm' },
    ],
    category: 'Herramientas de mano',
    subcategory: 'Mazas y martillos',
    group: 'HERRAMIENTAS DE MANO',
  },
  {
    id: 62,
    name: 'Llave Crique 1/2" 72 Dientes Reversible',
    brand: 'Facom',
    sku: 'FAC-LCR72',
    price: '$45.000',
    stock: 'available',
    images: [IMG_SAW],
    description: 'Llave crique de alta resistencia con encastre 1/2" y mecanismo de 72 dientes para giro de 5°. Selector de sentido reversible. Mango con antideslizante en goma para mejor agarre en posiciones difíciles.',
    specs: [
      { label: 'Encastre', value: '1/2"' },
      { label: 'Dientes', value: '72' },
      { label: 'Ángulo de acción', value: '5°' },
      { label: 'Par máximo', value: '135 Nm' },
    ],
    category: 'Herramientas de mano',
    subcategory: 'Llaves crique',
    group: 'HERRAMIENTAS DE MANO',
  },
  {
    id: 63,
    name: 'Palanca de Fuerza 1/2" 500mm',
    brand: 'KS Tools',
    sku: 'KST-PFZ500',
    price: '$38.000',
    stock: 'low',
    images: [IMG_SAW],
    description: 'Palanca de fuerza (llave de tubo) encastre 1/2" de 500mm para aplicación de torque elevado en tornillos y tuercas de alta resistencia. Acero CrMo forjado con mango antideslizante.',
    specs: [
      { label: 'Encastre', value: '1/2"' },
      { label: 'Longitud', value: '500 mm' },
      { label: 'Material', value: 'CrMo forjado' },
    ],
    category: 'Herramientas de mano',
    subcategory: 'Palancas de fuerza',
    group: 'HERRAMIENTAS DE MANO',
  },
  {
    id: 64,
    name: 'Extractor de Engranajes 3 Brazos',
    brand: 'Gedore',
    sku: 'GED-EXT3B',
    price: '$35.200',
    stock: 'available',
    images: [IMG_SAW],
    description: 'Extractor de engranajes y rodamientos de 3 brazos ajustables para desmontaje sin daño. Tornillo central de alta resistencia con cabeza cuadrada para llave de tubo. Brazos reversibles para extracción interna y externa.',
    specs: [
      { label: 'Brazos', value: '3 reversibles' },
      { label: 'Apertura máx.', value: '200 mm' },
      { label: 'Tornillo', value: 'M14 CrMo' },
    ],
    category: 'Herramientas de mano',
    subcategory: 'Extractores',
    group: 'HERRAMIENTAS DE MANO',
  },
  {
    id: 65,
    name: 'Tubo Especial para Precalentadores 10mm',
    brand: 'Stahlwille',
    sku: 'STW-TSP10',
    price: '$8.900',
    stock: 'available',
    images: [IMG_SAW],
    description: 'Tubo especial bihaxa de 10mm para desmontaje y montaje de precalentadores (bujías de incandescencia) en motores diesel. Diseño bihexagonal para mejor agarre y acero de alta resistencia para trabajar en caliente.',
    specs: [
      { label: 'Medida', value: '10 mm bihex' },
      { label: 'Uso', value: 'Precalentadores diesel' },
      { label: 'Encastre', value: '3/8"' },
    ],
    category: 'Herramientas de mano',
    subcategory: 'Tubos especiales',
    group: 'HERRAMIENTAS DE MANO',
  },
  {
    id: 66,
    name: 'Set Cuñas de Plástico Desmontaje 4 piezas',
    brand: 'Beta Tools',
    sku: 'BTA-CUP04',
    price: '$6.500',
    stock: 'available',
    images: [IMG_SAW],
    description: 'Set de 4 cuñas de plástico técnico para desmontaje de tapizados, molduras, tableros y paneles interiores sin rallar ni dañar las superficies. Polipropileno reforzado con fibra de vidrio.',
    specs: [
      { label: 'Piezas', value: '4' },
      { label: 'Material', value: 'PP reforzado FV' },
      { label: 'Uso', value: 'Interiores y molduras' },
    ],
    category: 'Herramientas de mano',
    subcategory: 'Varios',
    group: 'HERRAMIENTAS DE MANO',
  },

  // HERRAMIENTAS DE MANO — Herramientas de precisión y medición
  {
    id: 67,
    name: 'Calibre Digital 150mm 0.01mm',
    brand: 'Mitutoyo',
    sku: 'MIT-CDG150',
    price: '$38.000',
    stock: 'available',
    images: [IMG_MEAS],
    description: 'Calibre Vernier digital de 150mm con resolución de 0,01mm para medición de dimensiones internas, externas y profundidad. Display LCD de alta resolución. Para la mecánica de precisión es la herramienta de medición fundamental.',
    specs: [
      { label: 'Rango', value: '0–150 mm' },
      { label: 'Resolución', value: '0,01 mm' },
      { label: 'Display', value: 'LCD digital' },
      { label: 'IP', value: 'IP40' },
    ],
    category: 'Herramientas de precisión y medición',
    subcategory: 'Para la mecánica',
    group: 'HERRAMIENTAS DE MANO',
  },
  {
    id: 68,
    name: 'Nivel Láser Autonivelante 360°',
    brand: 'Bosch',
    sku: 'BSH-NLA360',
    price: '$125.000',
    stock: 'available',
    images: [IMG_MEAS],
    description: 'Nivel láser autonivelante de líneas cruzadas 360° para trabajos de construcción. Proyecta líneas horizontales y verticales con alcance de 20 metros. Montaje en trípode y magnético. Para la construcción garantiza alineación perfecta en instalaciones y revestimientos.',
    specs: [
      { label: 'Alcance', value: '20 m' },
      { label: 'Precisión', value: '±0,3 mm/m' },
      { label: 'Autonivelación', value: '±4°' },
      { label: 'Protección', value: 'IP54' },
    ],
    category: 'Herramientas de precisión y medición',
    subcategory: 'Para la construcción',
    group: 'HERRAMIENTAS DE MANO',
  },

  // HERRAMIENTAS DE MANO — Insertos
  {
    id: 69,
    name: 'Kit Insertos M6 M8 M10 con Mecha 30 unidades',
    brand: 'Böllhoff',
    sku: 'BOL-KIM30',
    price: '$32.500',
    stock: 'available',
    images: [IMG_SAW],
    description: 'Kit completo de 30 insertos roscados de acero inoxidable A2 en medidas M6, M8 y M10, con mecha y macho de roscar a juego. Ideal para reparación de roscas dañadas en aluminio y plástico.',
    specs: [
      { label: 'Medidas', value: 'M6, M8, M10' },
      { label: 'Unidades', value: '10 de cada medida' },
      { label: 'Material', value: 'Acero inoxidable A2' },
      { label: 'Incluye', value: 'Mecha HSS + macho' },
    ],
    category: 'Insertos',
    subcategory: 'Insertos en kit (con mecha y macho)',
    group: 'HERRAMIENTAS DE MANO',
  },
  {
    id: 70,
    name: 'Insertos Roscados M8 Solo Rosca 50 unidades',
    brand: 'Würth',
    sku: 'WRT-ISR50M8',
    price: '$14.800',
    stock: 'low',
    images: [IMG_SAW],
    description: 'Bolsa de 50 insertos roscados M8 de acero inoxidable A2 para colocación en aluminio, plástico y materiales blandos. Solo rosca, sin mecha ni macho. Para compra de recambio.',
    specs: [
      { label: 'Medida', value: 'M8 × 1,25' },
      { label: 'Unidades', value: '50' },
      { label: 'Material', value: 'A2 inox' },
    ],
    category: 'Insertos',
    subcategory: 'Insertos solo rosca (sin mecha y macho)',
    group: 'HERRAMIENTAS DE MANO',
  },

  // TALLER Y EQUIPAMIENTO — Mobiliario para talleres
  {
    id: 71,
    name: 'Tablero Perforado 60×90cm con Ganchos',
    brand: 'Lista',
    sku: 'LST-TPF6090',
    price: '$42.000',
    stock: 'available',
    images: [IMG_SAW],
    description: 'Tablero perforado de acero galvanizado 60×90cm para organización de herramientas en taller. Incluye kit de 20 ganchos de diferentes tamaños para llaves, destornilladores y alicates.',
    specs: [
      { label: 'Medidas', value: '600 × 900 mm' },
      { label: 'Material', value: 'Acero galvanizado' },
      { label: 'Perforación', value: 'Cada 25 mm' },
      { label: 'Ganchos incluidos', value: '20' },
    ],
    category: 'Mobiliario para talleres',
    subcategory: 'Tableros',
    group: 'TALLER Y EQUIPAMIENTO',
  },
  {
    id: 72,
    name: 'Banco de Trabajo Metálico 1200mm',
    brand: 'Sidamo',
    sku: 'SID-BTM120',
    price: '$185.000',
    stock: 'available',
    images: [IMG_SAW],
    description: 'Banco de trabajo metálico de 1200mm de largo con superficie de madera MDF de 40mm. Estructura de tubo rectangular 50×50 pintada al horno. Capacidad de carga de 500kg con estante inferior.',
    specs: [
      { label: 'Largo', value: '1.200 mm' },
      { label: 'Profundidad', value: '600 mm' },
      { label: 'Altura', value: '850 mm' },
      { label: 'Capacidad carga', value: '500 kg' },
    ],
    category: 'Mobiliario para talleres',
    subcategory: 'Bancos de trabajo',
    group: 'TALLER Y EQUIPAMIENTO',
  },
  {
    id: 73,
    name: 'Cajonera Rodante 7 Cajones con Llave',
    brand: 'Kennedy',
    sku: 'KEN-CRD07',
    price: '$225.000',
    stock: 'available',
    images: [IMG_SAW],
    description: 'Cajonera rodante de acero de 7 cajones con cerradura de seguridad para taller mecánico. Rieles de bolas de extensión total. Capacidad total de carga de 200kg. Ruedas giratorias de 75mm con freno.',
    specs: [
      { label: 'Cajones', value: '7' },
      { label: 'Material', value: 'Acero 0,9 mm' },
      { label: 'Capacidad total', value: '200 kg' },
      { label: 'Ruedas', value: '2 fijas + 2 giratorias con freno' },
    ],
    category: 'Mobiliario para talleres',
    subcategory: 'Cajoneras / Mesas rodantes',
    group: 'TALLER Y EQUIPAMIENTO',
  },
  {
    id: 74,
    name: 'Armario Metálico con Llave 90×45×185cm',
    brand: 'Presto',
    sku: 'PRS-ARM185',
    price: '$320.000',
    stock: 'available',
    images: [IMG_SAW],
    description: 'Armario metálico de 4 estantes regulables y puerta doble con cerradura de llave para almacenamiento seguro de herramientas, EPP y materiales en taller. Pintado al horno en gris claro.',
    specs: [
      { label: 'Ancho', value: '900 mm' },
      { label: 'Profundidad', value: '450 mm' },
      { label: 'Alto', value: '1.850 mm' },
      { label: 'Estantes', value: '4 regulables' },
    ],
    category: 'Mobiliario para talleres',
    subcategory: 'Organizadores - Armarios - Cajas - Alacenas',
    group: 'TALLER Y EQUIPAMIENTO',
  },
  {
    id: 75,
    name: 'Lámpara LED de Trabajo Recargable 20W',
    brand: 'Streamlight',
    sku: 'STR-LLP20',
    price: '$35.000',
    stock: 'low',
    images: [IMG_ELEC],
    description: 'Lámpara de trabajo LED de 20W con batería recargable de litio. 3 modos de iluminación (100%, 50%, 30%) con autonomía de hasta 8 horas. Gancho plegable y base magnética para fijación en superficies metálicas.',
    specs: [
      { label: 'Potencia LED', value: '20 W' },
      { label: 'Flujo luminoso', value: '1.800 lm' },
      { label: 'Autonomía', value: 'Hasta 8 h' },
      { label: 'Carga', value: 'USB-C' },
    ],
    category: 'Mobiliario para talleres',
    subcategory: 'Iluminación',
    group: 'TALLER Y EQUIPAMIENTO',
  },
  {
    id: 76,
    name: 'Recolector de Aceite Portátil 8L con Bandeja',
    brand: 'Draper',
    sku: 'DRP-RAP08',
    price: '$28.500',
    stock: 'available',
    images: [IMG_SAW],
    description: 'Recolector de aceite portátil de 8 litros con bandeja de vaciado de 30×30cm. Para cambio de aceite de autos en talleres de lubricentro. Tapa sellada con filtro de vapor y ruedas para transporte.',
    specs: [
      { label: 'Capacidad', value: '8 L' },
      { label: 'Bandeja', value: '300 × 300 mm' },
      { label: 'Peso vacío', value: '1,8 kg' },
    ],
    category: 'Mobiliario para talleres',
    subcategory: 'Recolectoras de líquidos y fluidos',
    group: 'TALLER Y EQUIPAMIENTO',
  },
  {
    id: 77,
    name: 'Morsa de Banco 100mm Tornillo Giratorio',
    brand: 'Wilton',
    sku: 'WIL-MBG100',
    price: '$68.000',
    stock: 'available',
    images: [IMG_SAW],
    description: 'Morsa de banco de 100mm de apertura con base giratoria 360°. Mandíbulas de acero tratado térmicamente intercambiables. Para fijación de piezas en banco de trabajo de taller y carpintería.',
    specs: [
      { label: 'Apertura máx.', value: '100 mm' },
      { label: 'Profundidad mandíbula', value: '60 mm' },
      { label: 'Base', value: 'Giratoria 360°' },
      { label: 'Peso', value: '5 kg' },
    ],
    category: 'Mobiliario para talleres',
    subcategory: 'Morsas',
    group: 'TALLER Y EQUIPAMIENTO',
  },
  {
    id: 78,
    name: 'Caballetes Metálicos Par 500kg c/u',
    brand: 'Stanley',
    sku: 'STN-CAB500',
    price: '$45.000',
    stock: 'available',
    images: [IMG_SAW],
    description: 'Par de caballetes metálicos de 500kg de capacidad cada uno para soporte seguro de vehículos durante trabajos mecánicos. Altura regulable en 3 posiciones. Construcción de acero con pintura anticorrosión.',
    specs: [
      { label: 'Capacidad', value: '500 kg c/u' },
      { label: 'Altura', value: '280–420 mm' },
      { label: 'Base', value: '350 × 250 mm' },
    ],
    category: 'Mobiliario para talleres',
    subcategory: 'Caballetes',
    group: 'TALLER Y EQUIPAMIENTO',
  },
  {
    id: 79,
    name: 'Carro Portaherramientas Plegable con Bolsas',
    brand: 'Keter',
    sku: 'KET-CPH01',
    price: '$58.000',
    stock: 'out',
    images: [IMG_SAW],
    description: 'Carro portaherramientas plegable con ruedas de alta resistencia y bolsas laterales de tela Oxford 600D. Para transporte de herramientas en obra y taller. Estructura de aluminio extruido.',
    specs: [
      { label: 'Carga máx.', value: '25 kg' },
      { label: 'Ruedas', value: '2 × 200 mm' },
      { label: 'Plegado', value: 'Sí, almacenaje compacto' },
    ],
    category: 'Mobiliario para talleres',
    subcategory: 'Otros',
    group: 'TALLER Y EQUIPAMIENTO',
  },

  // TALLER Y EQUIPAMIENTO — Sin subcategorías
  {
    id: 80,
    name: 'Suscripción ALLDATA Diagnóstico 1 año',
    brand: 'Alldata',
    sku: 'ALL-DIG1Y',
    price: '$25.000',
    stock: 'available',
    images: [IMG_MEAS],
    description: 'Suscripción de 1 año al software de diagnóstico técnico automotriz ALLDATA con acceso a manuales de reparación, diagramas eléctricos, valores de torque y procedimientos de calibración para todas las marcas.',
    specs: [
      { label: 'Duración', value: '12 meses' },
      { label: 'Acceso', value: 'Online / offline' },
      { label: 'Vehículos', value: 'Todas las marcas' },
    ],
    category: 'Libros y softwares para taller',
    subcategory: '',
    group: 'TALLER Y EQUIPAMIENTO',
  },
  {
    id: 81,
    name: 'Kit Detailing Profesional 12 productos',
    brand: "Meguiar's",
    sku: 'MEG-KDP12',
    price: '$85.000',
    stock: 'available',
    images: [IMG_SAW],
    description: 'Kit completo de detailing (estética vehicular) profesional con 12 productos: shampoo, cera, sellador, pulidor, limpiador de llantas, limpiador interior y acondicionador de gomas y plásticos.',
    specs: [
      { label: 'Productos', value: '12' },
      { label: 'Tipo', value: 'Detailing profesional' },
      { label: 'Presentación', value: 'Kit con bolso' },
    ],
    category: 'Detailing (estética vehicular)',
    subcategory: '',
    group: 'TALLER Y EQUIPAMIENTO',
  },

  // CONSUMIBLES — Consumibles para la industria
  {
    id: 82,
    name: 'Formajuntas Gris Silicona RTV 80g',
    brand: 'Permatex',
    sku: 'PMX-FGS80',
    price: '$3.800',
    stock: 'available',
    images: [IMG_SAW],
    description: 'Formajuntas silicona RTV gris de alta temperatura hasta 343°C para tapas de válvulas, cárteres y juntas de motor. Resistente a aceites y refrigerantes. Sellado inmediato al contacto.',
    specs: [
      { label: 'Contenido', value: '80 g' },
      { label: 'Temperatura máx.', value: '343°C' },
      { label: 'Tiempo curado', value: '24 h' },
      { label: 'Color', value: 'Gris' },
    ],
    category: 'Consumibles para la industria',
    subcategory: 'Formajuntas y pegamentos',
    group: 'CONSUMIBLES',
  },
  {
    id: 83,
    name: 'Silicona Neutra Multiusos Transparente 280ml',
    brand: 'Dow Corning',
    sku: 'DOW-SNT280',
    price: '$2.900',
    stock: 'low',
    images: [IMG_SAW],
    description: 'Silicona neutra multiusos transparente de 280ml para sellado de juntas, vidrios y metacrilato en industria y construcción. No ataca metales, espejos ni superficies sensibles al ácido.',
    specs: [
      { label: 'Contenido', value: '280 ml' },
      { label: 'Tipo', value: 'Neutra' },
      { label: 'Temperatura uso', value: '-50°C a +150°C' },
    ],
    category: 'Consumibles para la industria',
    subcategory: 'Siliconas',
    group: 'CONSUMIBLES',
  },
  {
    id: 84,
    name: 'Lubricante Penetrante WD-40 400ml',
    brand: 'WD-40',
    sku: 'WD40-400',
    price: '$4.500',
    stock: 'available',
    images: [IMG_SAW],
    description: 'Aerosol lubricante penetrante multifunción de 400ml para afloje de tornillos oxidados, protección anticorrosión, limpieza de contactos y lubricación ligera de mecanismos.',
    specs: [
      { label: 'Contenido', value: '400 ml' },
      { label: 'Presentación', value: 'Aerosol' },
      { label: 'Usos', value: 'Penetrante, lubricante, protector' },
    ],
    category: 'Consumibles para la industria',
    subcategory: 'Aerosoles lubricantes y otros',
    group: 'CONSUMIBLES',
  },
  {
    id: 85,
    name: 'Grasa Multipropósito Lithium 500g',
    brand: 'Mobilgrease',
    sku: 'MOB-GML500',
    price: '$3.200',
    stock: 'available',
    images: [IMG_SAW],
    description: 'Grasa consistente de litio multipropósito de 500g para engrase de rodamientos, bujes, rótulas y guías de suspensión. Resistente al agua y con protección anticorrosión de largo plazo.',
    specs: [
      { label: 'Contenido', value: '500 g' },
      { label: 'Base', value: 'Litio' },
      { label: 'Temperatura uso', value: '-25°C a +120°C' },
    ],
    category: 'Consumibles para la industria',
    subcategory: 'Grasas y aceites',
    group: 'CONSUMIBLES',
  },
  {
    id: 86,
    name: 'Desengrasante Industrial Concentrado 5L',
    brand: 'Würth',
    sku: 'WRT-DIC05L',
    price: '$18.500',
    stock: 'available',
    images: [IMG_SAW],
    description: 'Desengrasante industrial concentrado de 5 litros para limpieza de piezas metálicas, motores y bancos de trabajo. Sin disolventes clorados. Dilución hasta 1:10 para uso general.',
    specs: [
      { label: 'Contenido', value: '5 L' },
      { label: 'Dilución', value: '1:3 a 1:10' },
      { label: 'pH', value: '11,5' },
      { label: 'Biodegradable', value: 'Sí' },
    ],
    category: 'Consumibles para la industria',
    subcategory: 'Artículos para la limpieza',
    group: 'CONSUMIBLES',
  },
  {
    id: 87,
    name: 'Guantes Nitrilo Talla L Pack 50 unidades',
    brand: 'Ansell',
    sku: 'ANS-GNL50',
    price: '$8.900',
    stock: 'available',
    images: [IMG_SAW],
    description: 'Guantes desechables de nitrilo talla L sin polvo, resistentes a aceites, grasas y solventes ligeros. Para uso en taller mecánico, laboratorio y manejo de lubricantes.',
    specs: [
      { label: 'Material', value: 'Nitrilo 4 mil' },
      { label: 'Talla', value: 'L' },
      { label: 'Unidades', value: '50' },
      { label: 'Sin polvo', value: 'Sí' },
    ],
    category: 'Consumibles para la industria',
    subcategory: 'Guantes',
    group: 'CONSUMIBLES',
  },
  {
    id: 88,
    name: 'Pack Lijas al Agua Surtido P220-P2000 10u',
    brand: 'Klingspor',
    sku: 'KLG-LJA10',
    price: '$5.500',
    stock: 'low',
    images: [IMG_GRIND],
    description: 'Pack de 10 lijas al agua surtidas en granos P220, P400, P800, P1200 y P2000 para trabajo de acabado fino en metales y superficies de carrocería antes de pintura.',
    specs: [
      { label: 'Granos', value: 'P220–P2000' },
      { label: 'Unidades', value: '10 (2 de cada grano)' },
      { label: 'Tipo', value: 'Húmedo / seco' },
    ],
    category: 'Consumibles para la industria',
    subcategory: 'Lijas',
    group: 'CONSUMIBLES',
  },
  {
    id: 89,
    name: 'Discos de Corte Inox 115×1mm Pack 5 unidades',
    brand: 'Rhodius',
    sku: 'RHO-DCX5',
    price: '$7.200',
    stock: 'available',
    images: [IMG_GRIND],
    description: 'Pack de 5 discos de corte para amoladora de 115mm x 1mm de espesor para corte de acero inoxidable, acero al carbono y metales no ferrosos. Mínima rebaba y rápida disipación del calor.',
    specs: [
      { label: 'Diámetro', value: '115 mm' },
      { label: 'Espesor', value: '1 mm' },
      { label: 'Eje', value: '22,2 mm' },
      { label: 'RPM máx.', value: '13.300' },
    ],
    category: 'Consumibles para la industria',
    subcategory: 'Discos de corte',
    group: 'CONSUMIBLES',
  },
  {
    id: 90,
    name: 'Set Mechas HSS para Acero 13 piezas',
    brand: 'Bosch',
    sku: 'BSH-SMH13',
    price: '$28.500',
    stock: 'available',
    images: [IMG_ELEC],
    description: 'Set de 13 mechas (brocas) HSS para acero en estuche metálico, de 1,5 a 6,5mm. Material HSS-R laminado en frío para perforación de acero, hierro y metales no ferrosos con taladro eléctrico o banco.',
    specs: [
      { label: 'Medidas', value: '1,5–6,5 mm (13 diámetros)' },
      { label: 'Material', value: 'HSS-R' },
      { label: 'Estuche', value: 'Metálico' },
    ],
    category: 'Consumibles para la industria',
    subcategory: 'Mechas',
    group: 'CONSUMIBLES',
  },
  {
    id: 91,
    name: 'Cepillo de Copa para Amoladora 115mm',
    brand: 'Osborn',
    sku: 'OSB-CCA115',
    price: '$6.800',
    stock: 'available',
    images: [IMG_GRIND],
    description: 'Cepillo de copa de alambre trenzado de 115mm para amoladora angular. Para remoción de óxido, pintura vieja y escoria de soldadura en superficies metálicas. Vástago roscado M14.',
    specs: [
      { label: 'Diámetro', value: '115 mm' },
      { label: 'Tipo', value: 'Copa alambre trenzado' },
      { label: 'Rosca', value: 'M14' },
      { label: 'RPM máx.', value: '6.500' },
    ],
    category: 'Consumibles para la industria',
    subcategory: 'Cepillos para amoladora y taladro',
    group: 'CONSUMIBLES',
  },

  // CONSUMIBLES — Sin subcategorías
  {
    id: 92,
    name: 'Manguera de Jardín 25m 3/4" con Carrete',
    brand: 'Fitt',
    sku: 'FIT-MJC25',
    price: '$18.500',
    stock: 'available',
    images: [IMG_SAW],
    description: 'Manguera de jardín de 3/4" con 25 metros de largo y carrete automático de aluminio. Material PVC tricapa reforzado con malla de poliéster, resistente a UV y temperaturas extremas.',
    specs: [
      { label: 'Largo', value: '25 m' },
      { label: 'Diámetro', value: '3/4"' },
      { label: 'Presión máx.', value: '20 bar' },
      { label: 'Carrete', value: 'Aluminio con tope' },
    ],
    category: 'Artículos para el hogar y jardín',
    subcategory: '',
    group: 'CONSUMIBLES',
  },
  {
    id: 93,
    name: 'Mezclador para Taladro Pintura/Cemento 120mm',
    brand: 'Wolfcraft',
    sku: 'WLF-MTD120',
    price: '$8.200',
    stock: 'low',
    images: [IMG_ELEC],
    description: 'Mezclador en espiral de 120mm para taladro eléctrico. Para mezcla de pinturas, adhesivos, yesos, cementos y morteros para la construcción. Vástago hexagonal 1/2" para uso con taladro y atornillador.',
    specs: [
      { label: 'Diámetro', value: '120 mm' },
      { label: 'Largo', value: '600 mm' },
      { label: 'Encastre', value: '1/2" hex' },
    ],
    category: 'Herramientas para la construcción',
    subcategory: '',
    group: 'CONSUMIBLES',
  },
  {
    id: 94,
    name: 'Cinta de Medir 5m Automática con Freno',
    brand: 'Stanley',
    sku: 'STN-CME05',
    price: '$6.800',
    stock: 'available',
    images: [IMG_MEAS],
    description: 'Cinta métrica de 5 metros con carcasa de ABS reforzada, cinta de acero templado con laminado nylon y freno automático. Para medición universal en obra, hogar y taller.',
    specs: [
      { label: 'Longitud', value: '5 m' },
      { label: 'Ancho cinta', value: '19 mm' },
      { label: 'Graduación', value: '1 mm' },
      { label: 'Carcasa', value: 'ABS reforzado' },
    ],
    category: 'Herramientas y accesorios universales',
    subcategory: '',
    group: 'CONSUMIBLES',
  },
  {
    id: 95,
    name: 'Termo Stanley Classic 1L Acero Inoxidable',
    brand: 'Stanley',
    sku: 'STN-TRM01L',
    price: '$28.000',
    stock: 'out',
    images: [IMG_SAW],
    description: 'Termo Stanley Classic de 1 litro en acero inoxidable 18/8 con aislamiento al vacío. Mantiene bebidas calientes hasta 24 horas y frías hasta 8 horas. Tapa-vaso con sistema rosca. El clásico de los talleres y obras.',
    specs: [
      { label: 'Capacidad', value: '1 L' },
      { label: 'Material', value: 'Acero inox 18/8' },
      { label: 'Calor', value: 'Hasta 24 h' },
      { label: 'Frío', value: 'Hasta 8 h' },
    ],
    category: 'Termos y mates',
    subcategory: '',
    group: 'CONSUMIBLES',
  },

  // Extra para cobertura de búsqueda "soldadura"
  {
    id: 96,
    name: 'Soldadora TIG 200A con Pedal de Control',
    brand: 'Miller Electric',
    sku: 'MIL-TIG200',
    price: '$285.000',
    stock: 'available',
    images: [IMG_ELEC],
    description: 'Soldadora TIG de 200A para soldadura de acero inoxidable, aluminio y titanio con máximo control del arco. El pedal de control permite modular la corriente durante la soldadura para costuras perfectas. Incluye antorcha WP-17 y regulador de argón para soldadura de precisión.',
    specs: [
      { label: 'Corriente máx.', value: '200 A' },
      { label: 'Proceso', value: 'TIG / MMA' },
      { label: 'Voltaje', value: '220V 50Hz' },
      { label: 'Ciclo de trabajo', value: '60% a 150A' },
      { label: 'Peso', value: '12 kg' },
    ],
    category: 'Máquinas y herramientas eléctricas',
    subcategory: 'Soldadoras',
    group: 'HERRAMIENTAS ELÉCTRICAS',
  },
]

export function getProductById(id: number): Product | undefined {
  return products.find((p) => p.id === id)
}

export function getAllProducts(): Product[] {
  return products
}
